name: Setup PNPM
description: "Sets up PNPM"

inputs:
  node-version:
    description: 'Node Version'
    required: true

runs:
  using: "composite"
  steps:
    - name: PNPM Install
      shell: bash
      run: 'pnpm install'

    - name: DVC Pull
      shell: bash
      run: 'dvc pull'
