name: Build Docs
description: "Build Documentation Site"

inputs:
  gdrive_credentials_data:  # id of input
    description: 'Path to GDrive Credentials Data'
    required: true

runs:
  using: "composite"
  steps:
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     detached: true

    - name: 'Setup DVC & Pull Models'
      uses: ./.github/actions/setup-dvc
      with:
        gdrive_credentials_data: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}          

    - name: 'Setup PNPM'
      uses: ./.github/actions/setup-pnpm

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install

    - name: 'Build'
      shell: bash
      working-directory: ./docs
      run: pnpm build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/build
