# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/models"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/scripts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
