packages:
  - 'dev/**'
  - 'packages/**'
  - 'internals/**'
  - 'models/**'
  - 'scripts/**'
  - 'docs/**'
  # exclude packages that are inside demo directories
  - '!models/**/demo/**'
  - '!dev/browser/public/models/**'
