packages:
  - 'dev/**'
  - 'packages/**'
  - 'internals/**'
  - 'models/**'
  - 'docs/**'
  - 'tmp/bundlers/**'
  # exclude packages that are inside demo directories
  - '!models/**/demo/**'
  - '!dev/browser/public/models/**'
  - '!docs/workers/upscale/**'
