apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    name: Testing Playwright Support
    tags:
      - e2e
    build: "$BUILD_ID"
playwright:
  version: 1.7.1
  projectPath: tests/
docker:
  fileTransfer: mount
suites:
  - name: "saucy test"
    platformName: "Windows 10"
    testMatch: '**/*.js'
    env:
      hello: world

    params:
      browserName: "firefox"
      headful: false
      slowMo: 1000
