/*****
 * Pins the current version of UpscalerJS to the correct CDN path, so that version x.x.x of upscaler
 *      points to the same version of @upscaler/models
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const UPSCALERJS_ROOT = path.resolve(ROOT, 'packages/upscalerjs');

const MODELS_PACKAGE = require(path.resolve(ROOT, 'packages/models/package.json'));

const modelsVersion = MODELS_PACKAGE['version'];

console.log(`Pinning version ${modelsVersion} in CDN definition`);

const writeConstantsFile = (version) => {
  const constants = [
    { key: 'ROOT', val: `https://unpkg.com/@upscalerjs/models@${version}`},
  ];
  const contents = constants.map(({ key, val }) => `export const ${key} = '${val}';`).join('\n');
  fs.writeFileSync(
    path.resolve(UPSCALERJS_ROOT, 'src/constants.ts'), 
    `/*****\nThis is an autogenerated file. See scripts/pin-cdn.js for more information.\n*****/\n\n${contents}\n`
  );
}
writeConstantsFile(modelsVersion);
