blank_issues_enabled: false
contact_links:
  - name: Have questions or need support?
    url: https://github.com/thekevinscott/upscalerjs/discussions
    about: Please ask questions on the Discussions tab
