name = "upscale-dev"
main = "src/index.ts"
compatibility_date = "2022-08-10"
workers_dev = true
node_compat = true

[env.production]
name = "upscale-prod"
workers_dev = false
routes = [
	{ pattern = "upscale.upscalerjs.com", custom_domain = true }
]
