"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE = void 0;
var MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE;
(function (MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE) {
    MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE["UNDEFINED"] = "undefined";
    MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE["INVALID_MODEL_TYPE"] = "invalidModelType";
    MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE["MISSING_PATH"] = "missingPath";
})(MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE || (exports.MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE = MODEL_DEFINITION_VALIDATION_CHECK_ERROR_TYPE = {}));
