/*******************************************************************************

* This file is autogenerated. Do not edit directly

*******************************************************************************/
export default '/mnt/Castellan/code/esrgan/upscalerjs/scripts/bump_version.js';
