name: Setup PNPM
description: "Sets up PNPM"

inputs:
  node-version:
    description: 'Node Version'
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts

    - name: postinstall
      shell: bash
      run: pnpm postinstall

    - name: TFJS-node
      shell: bash
      run: pnpm rebuild @tensorflow/tfjs-node --build-addon-from-source

    - name: Install Puppeteer explicitly
      shell: bash
      run: node node_modules/puppeteer/install.js
