name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Docs
        uses: ./.github/actions/build-docs

  # Deployment job
  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/build/
  