name: 'Tests'
on: [pull_request]
jobs:
  ubuntu-job:
    name: 'Unit'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Building'
        run: yarn

      - name: 'Running test'
        run: yarn test:unit
