# https://github.com/dependabot/dependabot-core/issues/1736
name: Dependabot
on: pull_request_target
permissions: read-all
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 'Setup PNPM with Node 20'
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: 20

      - run: pnpm update:npm:dependencies

      - name: 'Commit and push lockfile updates'
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          if git diff --quiet && git diff --cached --quiet; then
            echo "No lockfile changes to commit"
            exit 0
          fi
          git add -A
          git commit -m "Update lockfiles"
          git push
